services:
  - type: web
    name: hp-monopoly-deal
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
